services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: unless-stopped

    environment:
      - CLUSTER_NAME=bigdata
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions_enabled=false

    ports:
      - "9870:9870"
      - "8020:8020"

    volumes:
      - namenode_data:/hadoop/dfs/name

    networks:
      - bigdata-net


  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: unless-stopped

    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_permissions_enabled=false

    ports:
      - "9864:9864"

    volumes:
      - datanode_data:/hadoop/dfs/data

    networks:
      - bigdata-net

volumes:
  namenode_data:
  datanode_data:

networks:
  bigdata-net: