agent.sources = source_exec
agent.channels = channel_hdfs channel_flink
agent.sinks = sink_hdfs sink_flink

agent.sources.source_exec.type = exec
agent.sources.source_exec.command = tail -F /var/log/myapp/events.json
agent.sources.source_exec.shell = /bin/bash -c
agent.sources.source_exec.restart = true
agent.sources.source_exec.restartThrottle = 1000

agent.sources.source_exec.selector.type = replicating

agent.sources.source_exec.channels = channel_hdfs channel_flink


# =========================
# CHANNEL HDFS
# =========================

agent.channels.channel_hdfs.type = file
agent.channels.channel_hdfs.checkpointDir = /var/lib/flume/checkpoint-hdfs
agent.channels.channel_hdfs.dataDirs = /var/lib/flume/data-hdfs


# =========================
# CHANNEL FLINK
# =========================

agent.channels.channel_flink.type = file
agent.channels.channel_flink.checkpointDir = /var/lib/flume/checkpoint-flink
agent.channels.channel_flink.dataDirs = /var/lib/flume/data-flink


# =========================
# SINK HDFS
# =========================

agent.sinks.sink_hdfs.type = hdfs
agent.sinks.sink_hdfs.hdfs.path = hdfs://namenode:8020/data/raw/ecommerce/logs

agent.sinks.sink_hdfs.hdfs.filePrefix = ecommerce-
agent.sinks.sink_hdfs.hdfs.fileSuffix = .json
agent.sinks.sink_hdfs.hdfs.fileType = DataStream
agent.sinks.sink_hdfs.hdfs.writeFormat = Text

agent.sinks.sink_hdfs.hdfs.rollInterval = 30
agent.sinks.sink_hdfs.hdfs.rollSize = 0
agent.sinks.sink_hdfs.hdfs.rollCount = 0

agent.sinks.sink_hdfs.channel = channel_hdfs


# =========================
# SINK FLINK
# =========================

agent.sinks.sink_flink.type = file_roll

agent.sinks.sink_flink.sink.directory = /var/lib/flink-input
agent.sinks.sink_flink.sink.rollInterval = 10

agent.sinks.sink_flink.channel = channel_flink